# ===========================
# Pipeline configuration file
# Example: single corpus run
# ===========================

# Output directory (will be created if missing)
output: "testing/single/single"

# Languages
# See the README for accepted language input formats
l1: "Catalan"
l2: "yue_Hani"

# Embedding model (choices: labse, comet, sonar)
model: "labse"
model_path: ""   # optional, if you want to point to a local model path

# Filtering thresholds
alignment_score: 0.75
langid_l1_prob: 0.5
langid_l2_prob: 0.5

# Pipeline steps to run (in order)
steps:
  - input
  - embeddings
  - langid
  - filter
  - dedup
  - normalise
  - bifixer


bifixer_flags: ["--ignore_segmentation", "--ignore_duplicates"]

# Input corpus (single)
input: ["", ""]
# start_from: ""
format: "plain_text"  # or "tsv"
